# Generated by Django 4.0.5 on 2022-07-15 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('serviceorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='client.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
