# Generated by Django 4.0.5 on 2022-07-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('subserviceorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subserviceorder',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.item'),
            preserve_default=False,
        ),
    ]
