# Generated by Django 4.0.5 on 2022-07-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subserviceorder', '0003_remove_subserviceorder_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subserviceorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subserviceorder',
            name='number',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
