# Generated by Django 4.0.5 on 2022-07-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subitem', '0001_initial'),
        ('subserviceorder', '0004_subserviceorder_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subserviceorder',
            name='item',
        ),
        migrations.AddField(
            model_name='subserviceorder',
            name='subitem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subitem.subitem'),
            preserve_default=False,
        ),
    ]
