# Generated by Django 4.0.5 on 2022-07-05 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subserviceorder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(auto_now_add=True, verbose_name='Início')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='Fim')),
                ('incidents', models.TextField(blank=True, null=True, verbose_name='Ocorrências')),
                ('period', models.IntegerField(blank=True, default=1, null=True, verbose_name='Periodo de tempo')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('qtd', models.IntegerField(blank=True, default=1, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idEmployee', to='authentication.employee', verbose_name='Colaborador')),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idServiceOrder', to='subserviceorder.subserviceorder', verbose_name='Ordem de Serviço')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idProcess', to='process.process', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Localização O.S',
                'verbose_name_plural': 'Localizar O.S',
                'ordering': ['-end'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalServiceOrderHistory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start', models.TimeField(blank=True, editable=False, verbose_name='Início')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='Fim')),
                ('incidents', models.TextField(blank=True, null=True, verbose_name='Ocorrências')),
                ('period', models.IntegerField(blank=True, default=1, null=True, verbose_name='Periodo de tempo')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('qtd', models.IntegerField(blank=True, default=1, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentication.employee', verbose_name='Colaborador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subserviceorder.subserviceorder', verbose_name='Ordem de Serviço')),
                ('process', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='process.process', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'historical Localização O.S',
                'verbose_name_plural': 'historical Localizar O.S',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
